---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by limin.
--- DateTime: 2026/6/1 09:52
---

local key = KEYS[1]
local value = ARGV[1]

local lockValue = redis.call("get", key)

if value == lockValue then
    return redis.call("del", key)
end
return 0