---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by limin.
--- DateTime: 2026/6/1 18:07
---

local voucherId = ARGV[1]
local userId = ARGV[2]

local orderId = ARGV[3]

local stockKey = "voucher:stock:" .. voucherId

local orderKey = "order:voucher:" .. voucherId


local currentStock = redis.call("get", stockKey)

if tonumber(currentStock) <= 0 then
    return 1
end

if redis.call("sismember", orderKey, userId ) == 1 then
    return 2
end

redis.call("incrby", stockKey, -1)
redis.call("sadd", orderKey, userId)
redis.call("xadd", "stream.orders", "*", "userId", userId, "voucherId", voucherId, "id", orderId)
return 0