spring:
  application:
    name: user-service
    address: 0.0.0.0

  cloud:
    # 网关自动注册 Nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos API地址
        username: nacos
        password: nacos
        register-enabled: true  # 开启自动注册（默认就是true）

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10

server:
  port: 8082

jwt:
  secret: abcdefghijklmn1234567890ABCDEFGHIJKLMN
  expire: 604800




mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto # 主键自增

management:
  server:
    # 可选：监控和业务同端口
    port: 8082
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:logback.xml